самостійна 2/app/feedback/models.py
from app import db
from datetime import datetime

class Feedback(db.Model):
    __tablename__ = "feedbacks"
    
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(25), unique=True)
    email = db.Column(db.String(100), unique=True)
    content = db.Column(db.String(250))
    createdAt = db.Column(db.DateTime, default=datetime.utcnow)
    
    def __init__(self, username, email, content):
        self.username = username
        self.email = email
        self.content = content

самостійна 2/app/feedback/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class AddFeedback(FlaskForm):
    username = StringField("Enter username", validators=[DataRequired("This field is required")])
    email = StringField("Enter email", validators=[DataRequired("This field is required")])
    content = TextAreaField("Eenter content", validators=[DataRequired("This field is required")])
    submit = SubmitField("Add")

самостійна 2/app/feedback/__init__.py
from flask import Blueprint

feedback = Blueprint("feedback", __name__, template_folder="templates/feedback")

самостійна 2/app/feedback/views.py
from flask import render_template, redirect, url_for, flash
from .forms import AddFeedback
from .models import Feedback
from app import db
from . import feedback


@feedback.route("/feedbacks", methods=["GET", "POST"])
def feedbacks():
    form = AddFeedback()
    feedbacks = Feedback.query.all()
    return render_template("feedbacks.html", form = form, feedbacks=feedbacks)


@feedback.route("/feedbacks/add", methods=["POST"])
def add():
    form = AddFeedback()
    
    if form.validate_on_submit():
        username = form.username.data
        email = form.email.data
        content = form.content.data
        
        feedback = Feedback(username, email, content)
        
        db.session.add(feedback)
        db.session.commit()
        
        flash("feedback add successfully", "success")
        
    return redirect(url_for("feedback.feedbacks"))


@feedback.route('/feedbacks/delete/<int:id>')
def delete(id):
    feedbaack = Feedback.query.filter_by(id=id).first_or_404()
    db.session.delete(feedbaack)
    db.session.commit()
    flash("feedback deleted successfully", "success")
    return redirect(url_for('feedback.feedbacks'))

самостійна 2/app/feedback/templates/feedback/feedbacks.html
{% from 'fieldMacro.html' import displayField %}
{% extends 'base.html' %}
{% block title %}Feedbacks{% endblock %}

{% block content %}
    <div class="container">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-lg-9 col-xl-7">
            <div class="mt-3">
                <form action="{{ url_for('feedback.add') }}" method="POST">
                    {{ form.csrf_token }}
                    {{ displayField(form.username, "Username") }}
                    {{ displayField(form.email, "Email") }}
                    {{ displayField(form.content, "Content") }}
                    <br>
                    {{ form.submit(class="btn btn-primary width-100") }}
                </form>
            </div>
            </div>
        </div>
        </div>

        
        <br><br><br><br>

        {% for item in feedbacks %}
            <div class="list-group">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ item.username }} | {{ item.email }}</h5>
                        <a href="{{ url_for('feedback.delete', id=item.id) }}">
                            <i class="bi bi-trash3-fill text-danger"></i>
                        </a>
                </div>
                <h4 class="mb-1 mt-10"><strong>{{ item.content }}</strong></h4>
                <small class="text-muted mt-30">{{ item.createdAt.strftime("%m/%d/%Y, %H:%M:%S") }}</small>
            </div>
            <br><hr><br>
        {% endfor %}
        
    </div>
    <br><br>
    
{% endblock %}