самостійна 2/app/portfolio/__init__.py
from flask import Blueprint

portfolio = Blueprint("portfolio", __name__, template_folder="templates/portfolio")

самостійна 2/app/portfolio/views.py
import os
from flask import render_template, redirect, url_for, request, abort
from datetime import datetime
from . import portfolio

@portfolio.route('/')
def home():
    osInfo = os.environ.get('OS')
    agent = request.user_agent
    time = datetime.now().strftime("%H:%M:%S")
    
    return render_template('home.html', agent=agent, time=time, osInfo=osInfo)


@portfolio.route('/page1')
def page1():
    osInfo = os.environ.get('OS')
    agent = request.user_agent
    time = datetime.now().strftime("%H:%M:%S")
    return render_template('page1.html', agent=agent, time=time, osInfo=osInfo)

@portfolio.route('/page2')
def page2():
    osInfo = os.environ.get('OS')
    agent = request.user_agent
    time = datetime.now().strftime("%H:%M:%S")
    return render_template('page2.html', agent=agent, time=time, osInfo=osInfo)

@portfolio.route('/page3')
def page3():
    osInfo = os.environ.get('OS')
    agent = request.user_agent
    time = datetime.now().strftime("%H:%M:%S")
    return render_template('page3.html', agent=agent, time=time, osInfo=osInfo)

@portfolio.route('/about')
def about():
    osInfo = os.environ.get('OS')
    agent = request.user_agent
    time = datetime.now().strftime("%H:%M:%S")
    return render_template('about.html', agent=agent, time=time, osInfo=osInfo)

самостійна 2/app/portfolio/templates/portfolio/about.html
{% extends "base.html" %}
{% block title %} About{% endblock %}

{% block css %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}">
{% endblock %}

{% block body %}
<div class="container">
    <h1> A more detailed biography can be found below</h1>

     <ul class="simple-list">
        <li>
            <a href="{{ url_for('portfolio.home') }}">Home</a>
        </li>
        <li>
            <a href="{{ url_for('portfolio.page1') }}">page 1</a>
        </li>
        <li>
            <a href="{{ url_for('portfolio.page2') }}">page 2</a>
        </li>
        <li>
            <a href="{{ url_for('portfolio.page3') }}">page 3</a>
        </li>
    </ul>
    <img src="/static/images/image5.jpg" alt="">
</div>
{% endblock %}

самостійна 2/app/portfolio/templates/portfolio/home.html
{% extends "base.html" %}
{% block title %} Home {% endblock %}

{% block body %}
{{ super() }}
    <div class="container">
        <div class="imgh">
            <img class="home-image" src="/static/images/flask.png" alt="Flask Image">
            <p class="flask-description">Це мій проект по Python-Flask</p>
        </div>
    </div>
{% endblock %}

самостійна 2/app/portfolio/templates/portfolio/page1.html
{% extends 'base.html' %}



{% block body %}
<div class="container">
    <h2>Page 1</h2>
    <p class="biography">Привіт! Мене звати Юля, мені 19 років, і я студентка інженерії програмного забезпечення. Захоплююсь програмуванням та розробкою, і намагаюся поєднати теорію з практикою.</p>
    <table class="bio-table">
      <tr>
        <th>Дата народження</th>
        <th>Рік</th>
    </tr>
    <tr>
        <td> 4 березня</td>
        <td>2004</td>
    </tr>
    </table>
    <img src="/static/images/png1.png" alt="Зображення 1"><br><br>
    <h4><a href="{{ url_for('portfolio.about') }}">Повернутися до біографії</a></h4>
</div>
{% endblock %}

самостійна 2/app/portfolio/templates/portfolio/page2.html
{% extends 'base.html' %}



{% block body %}
<div class="container">
    <h2>Page 2</h2>
    <p class="biography">У вільний час люблю займатись випічкою. Натхнення та нові рецепти беру з ютуб блогів. Ось мій рейтинг:</p>
    <table class="bio-table">
    <tr>
        <th>Назва каналу</th>
        <th>Підписники</th>
        <th>Національність</th>
    </tr>
    <tr>
        <td>Liza Glinskaya</td>
        <td>717 тисяч</td>
        <td>українка</td>
    </tr>
    <tr>
        <td>Cookers Show</td>
        <td>14 тисяч</td>
        <td>українка</td>
    </tr>
    <tr>
        <td>Євгенія Періг</td>
        <td>84 тисяч</td>
        <td> українка</td>
    </tr>

    </table>
    <img src="/static/images/png2.png" alt="Зображення 2"><br><br>
    <h4><a href="{{ url_for('portfolio.about') }}">Повернутися до біографії</a></h4>
</div>
{% endblock %}

самостійна 2/app/portfolio/templates/portfolio/page3.html
{% extends 'base.html' %}

{% block title %}Page 3{% endblock %}

{% block body %}
<div class="container">
    <h2>Сторінка 3</h2>
    <p>Також маю багато досвіду в танцях. Більше 10 років займалась різними стилями танцю.</p>
    <img src="/static/images/png3.png" alt="Зображення 1">
    <h4><a href="{{ url_for('portfolio.about') }}">Повернутися до біографії</a></h4>
</div>
{% endblock %}